M0-OnlinePlayersGUI:
  ReloadMessage: '&2Configuration has been reloaded.'
  NoPermission: '&2You do not have permission to this command.'
  HideButtonsOnSinglePage: false
  EssentialsXHook: false
  PreviousButton:
    Material: ENCHANTED_BOOK
    Name: '&cPrevious Page'
    Lore:
      - '&7Click to open previous page.'
  NextButton:
    Material: ENCHANTED_BOOK
    Name: '&aNext Page'
    Lore:
      - '&7Click to open next page.'
  GUI:
    Size: 18
    Title: '&2Online Players'
    UpdateOn:
      Join: true
      Leave: true
  PlayerDisplay:
    Name: '&6%player_name%'
    Lore:
      - '&2Right click to &ateleport&2 to the player.'
      - '&2Left click to &asay hi&2.'
    Commands:
      Left-Click:
        - 'tp %player_name%'
      Right-Click:
        - 'msg %player_name% Hello!'