M0-OnlinePlayersGUI:
  Name: '&6%player_name%'
  ReloadMessage: '&2Configuration has been reloaded.'
  NoPermission: '&2You do not have permission to this command.'
  UpdateOnJoin: true
  UpdateOnLeave: true
  Lore:
    - '&eRight click to ...'
    - '&eLeft click to ...'
  Commands:
    Left-Click:
      - 'say %player_name% Left click action..'
    Right-Click:
      - 'msg %player_name% Right click action..'
