
messages:
  reload: '&2Configuration has been reloaded.'
  no-permission: '&2You do not have permission to this command.'
  no-permission-conditional: '&2You do not have permission to view this GUI'
  toggle-visibility: '&2You have toggled your visibility in Online GUI.'

# Whether to hide buttons if there are not enough players
# to fill up more than one page
buttons-always-visible: false
# Hook to EssentialsX which will hide players
# in the GUI if they are vanished
essentialsx-hook: false
# Conditional display
# It will check whether the placeholder applies (is true) for the
# player and if not, it will exclude the player from the GUI
# https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
condition:
  required: false
  # Condition Operators:
  ## Text operators:
  # =, ==, eq, equal_to, equals — equals
  # !=, neq, ne, not_equal — not equals
  # ~=, ~~, contains, contains_string — contains
  # !~=, !~~, !contains, not_contains, not_contains_string — does not contain
  # starts, starts_with — starts with
  # ends, ends_with — ends with
  # matches, regex — matches regex
  # !matches, !regex, not_matches, not_regex — does not match regex
  #
  ## Digit operators:
  # >, gt, greater_than — greater than
  # <, lt, less_than — less than
  # >=, gte, greater_than_or_equal — greater than or equal
  # <=, lte, less_than_or_equal — less than or equal
  # =, ==, eq, equal_to, equals — equals
  # !=, neq, ne, not_equal — not equals
  # (All text operators above also work for digits, comparing as strings.)
  # Ex.: %player_health% == 20
  placeholder: "%checkitem_mat:DIRT%" # Requires CheckItem PAPI extension
  permission:
    required: false
    node: "permission.to.include.player"

player-display-material: 'PLAYER_HEAD'

previous-button:
  material: ENCHANTED_BOOK
  name: '&cPrevious Page'
  slot: 21
  lore:
    - '&7Click to open previous page.'

next-button:
  material: ENCHANTED_BOOK
  name: '&aNext Page'
  slot: 23
  lore:
    - '&7Click to open next page.'
# Player display configuration
# Every section supports placeholders
player-display:
  name: '&6%player_name%'
  lore:
    - '&2Right click to &ateleport&2 to the player.'
    - '&2Left click to &asay hi&2.'
  commands:
    left-click:
      - '[PLAYER] tp %player_name%'
    right-click:
      - '[PLAYER] msg %player_name% Hello, my name is %sender_name%.'
      - '[CONSOLE] msg %player_name% Hello! '
      - '[CLOSE]' # This will close the GUI.
    middle-click:
      - '[CLOSE]'

# GUI Slots:
# --------------------------
# 0  1  2  3  4  5  6  7  8
# 9  10 11 12 13 14 15 16 17
# 18 19 20 21 22 23 24 25 26
# 27 28 29 22 31 32 33 34 35
# 36 37 38 39 40 41 42 43 44
# 45 46 47 48 49 50 51 52 53
# --------------------------

# Size should be in increments of 9 and not
# lower than 9 or higher than 54
# 9 slots is one row
gui:
  size: 27
  title: '&2Online Players'
  update-on:
    join: true
    leave: true

# Custom Items
# These items will be displayed in the same row as
# the previous and next buttons are
# Available command actions:
# [MESSAGE] - Sends a message to the player: [MESSAGE] Hello, %player_name%!
# [CHAT] - Sends a chat message to the player: [CHAT] Hello, %player_name%!
# [TITLE] - Sends a title to the player: [TITLE] Hello, %player_name%!, 20, 60, 20
# [ACTIONBAR] - Sends an action bar message to the player: [ACTIONBAR] Hello, %player_name%!
# [SOUND] - Plays a sound to the player: [SOUND] ENTITY_EXPERIENCE_ORB_PICKUP, 1, 1
# [PLAYER] - Executes a command as the player: [PLAYER] /command %player_name%
# [CONSOLE] - Executes a command as the console: [CONSOLE] /command %player_name%
# [BROADCAST] - Broadcasts a message to the server: [BROADCAST] Hello, %player_name%!
# [PARTICLE] - Spawns a particle at the player's location: [PARTICLE] FLAME, 1, 0, 0, 0
custom-items:
  '1':
    material: RED_STAINED_GLASS_PANE
    slots:
      start: 0
      end: 8
    name: '&r'
    lore: []
    commands:
      left-click:
        - '[CLOSE]'
      right-click:
        - '[CLOSE]'
      middle-click:
        - '[CLOSE]'
  '2':
    material: RED_STAINED_GLASS_PANE
    slots:
      - 9
      - 17
      - 18
      - 19
      - 20
      - 22
      - 24
      - 25
      - 26
    name: '&r'
    lore: []

debug: false