M0-OnlinePlayersGUI:
  Name: '&6%player_name%' # PAPI placeholder
  ReloadMessage: '&2Configuration has been reloaded.'
  NoPermission: '&2You do not have permission to this command.'
  UpdateOnJoin: true
  UpdateOnLeave: true
  HideButtonsOnSinglePage: true # Hides the buttons if there's only one page
  PreviousPageMaterial: 'ENCHANTED_BOOK' # Has to be a valid material name
  PreviousPageName: '&cPrevious Page'
  NextPageMaterial: 'ENCHANTED_BOOK' # Has to be a valid material name
  NextPageName: '&aNext Page'
  GUISize: 54 # Size has to be in increments of 9 (+9 for page row).
  Lore: # Lore: []
    - '&eRight click to ...'
    - '&eLeft click to ...'
  Commands: # Commands: []
    Left-Click:
      - 'say %player_name% Left click action..'
    Right-Click:
      - 'msg %player_name% Right click action..'
