M0-OnlinePlayersGUI:
  Name: '&6%player%'
  ReloadMessage: '&2Configuration has been reloaded.'
  NoPermission: '&2You do not have permission to this command.'
  Lore:
  - '&eRight click to ...'
  - '&7Left click to ...'
  Commands:
    Left-Click:
      - 'msg %player% Left click action..'
    Right-Click:
      - 'msg %player% Right click action..'