name: M0-OnlinePlayersGUI
main: me.M0dii.OnlinePlayersGUI.Main
description: M0-OnlinePlayersGUI
version: 1.6
api-version: 1.16
author: M0dii
softdepend: [PlaceholderAPI]
commands:
  online:
    description: Online gui player list command.
    permission: m0onlinegui.see
    usage: /<command>
    aliases: [onlinegui]
permissions:
  m0onlinegui.see:
    description: Permission to see online player GUI.
    default: op
  m0onlinegui.reload:
    description: Permission to see reload the configuration.
    default: op