name: M0-OnlinePlayersGUI
main: me.M0dii.OnlinePlayersGUI.OnlineGUI
description: M0-OnlinePlayersGUI
version: 3.0-pre
api-version: 1.16
author: M0dii
softdepend: [PlaceholderAPI, EssentialsX]
commands:
  online:
    description: Online gui player list command.
    permission: m0onlinegui.command.onlinegui
    usage: /<command>
    aliases: [onlinegui]
permissions:
  m0onlinegui.command.onlinegui:
    description: Permission to see online player GUI.
    default: op
  m0onlinegui.command.reload:
    description: Permission to see reload the configuration.
    default: op
  m0onlinegui.command.toggleself:
    description: Permission to toggle self visibility in Online GUI.
    default: op
  m0onlinegui.hidden:
    description: Hide players from the GUI with this permission.
    default: op