name: Generate and Upload SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-and-upload-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate CycloneDX SBOM
        run: ./gradlew cyclonedxBom

      - name: Upload SBOM to Dependency Graph
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: build/reports/bom.json