name: Generate and Upload SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  generate-and-upload-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Generate CycloneDX SBOM
        run: ./gradlew cyclonedxBom

      - name: Verify SBOM file
        run: ls -l build/reports && head -40 build/reports/bom.json

      - name: Submit SBOM to GitHub Dependency Graph API
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_SBOM_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/vnd.cyclonedx+json" \
            --data-binary @build/reports/bom.json \
            https://api.github.com/repos/${{ github.repository }}/dependency-graph/sbom